serial_controller:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    timeout: 0.1

config:
  baudrate: 115200
  buffer_size: 256
  head_byte_1: 0x5A
  head_byte_2: 0xA5
  checksum: "CRC8"
  require_handshake: false
  enable_heartbeat: true
  qos_depth: 10
  heartbeat_timeout_ms: 3000

type_mappings:
  f32: "float"
  i32: "int32_t"
  u8:  "uint8_t"
  u16: "uint16_t"
  u32: "uint32_t"

messages:
  - name: "Heartbeat"
    id: 0x00
    direction: "tx"
    sub_topic: "/task/heartbeat"
    ros_msg: "std_msgs/msg/UInt32"
    fields:
      - { proto: "count", type: "u32", ros: "data" }

  - name: "Handshake"
    id: 0xFF
    direction: "both"
    sub_topic: "/task/handshake"
    pub_topic: "/task/handshake"
    ros_msg: "std_msgs/msg/UInt32"
    fields:
      - { proto: "protocol_hash", type: "u32", ros: "data" }
  
  # ── 底盘运动指令（Jetson → STM32）──
  - name: "CmdVel" #底盘CmdVel
    id: 0x01
    direction: "tx"
    sub_topic: "/serial/chassis_cmd"
    ros_msg: "geometry_msgs/msg/Twist"
    fields:
      - { proto: "turn_angle",    type: "f32", ros: "angular.z" }
      - { proto: "turn_wheels",   type: "f32", ros: "linear.z"  }
      - { proto: "forward_dist",  type: "f32", ros: "linear.x"  }
      - { proto: "drive_wheels",  type: "f32", ros: "linear.y"  }
      - { proto: "pickup_action", type: "f32", ros: "angular.x" }
      - { proto: "search_rotate", type: "f32", ros: "angular.y" }


  # ── 坡度数据（Jetson → STM32）──
  - name: "SlopeInfo" #坡度信息
    id: 0x03
    direction: "tx"
    sub_topic: "/serial/slope_info"
    ros_msg: "geometry_msgs/msg/Vector3"
    fields:
      - { proto: "angle_deg",   type: "f32", ros: "x" }
      - { proto: "horiz_dist",  type: "f32", ros: "y" }
      - { proto: "height_diff", type: "f32", ros: "z" }

  # ── 梅林方块导航指令（Jetson → STM32）──
  - name: "MeilinCmd" #梅林控制
    id: 0x04
    direction: "tx"
    sub_topic: "/serial/meilin_cmd"
    ros_msg: "geometry_msgs/msg/Twist"
    fields:
      - { proto: "next_block",   type: "f32", ros: "linear.x"  }
      - { proto: "climb_mode",   type: "f32", ros: "linear.y"  }
      - { proto: "slope_angle",  type: "f32", ros: "linear.z"  }
      - { proto: "block_height", type: "f32", ros: "angular.x" }
      - { proto: "detour",       type: "f32", ros: "angular.y" }

  - name: "GripperStatus" #夹爪状态
    id: 0x10
    direction: "rx"
    pub_topic: "/feedback/gripper"
    ros_msg: "std_msgs/msg/UInt8"
    fields:
      - { proto: "status", type: "u8", ros: "data" }
    # 0=空载  1=已抓取  2=已完成组装  3=错误

  - name: "AssemblyStatus" #组件状态
    id: 0x11
    direction: "rx"
    pub_topic: "/feedback/assembly"
    ros_msg: "std_msgs/msg/UInt8"
    fields:
      - { proto: "status", type: "u8", ros: "data" } 
      # 0=未组装  1=组装中  2=组装完成  3=失败

